---
title: "Untitled"
author: "JJayes"
date: "16/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(rvest)

knitr::purl("code/stockholm_archive_scraper.Rmd", documentation = 2)
```

## Purpose

Start with ingesting the data from the website.

### Robots.txt

```{r}
library(robotstxt)
get_robotstxt("https://stadsarkivet.stockholm/")
```

There's nothing here, so we can proceed.

### Trying for mantalsregister 1909

Want to get the table with the first elements

```{r}
url <- "https://sok.stadsarkivet.stockholm.se/Databas/mantalsregister-1909/Sok?sidindex=20"

get_table_data <- function(url) {
  html <- read_html(url)
  
  message(paste0("Getting data from", url))
  
  table <- html %>%
    html_node(".table") %>%
    html_table()

  table <- table %>%
    janitor::clean_names() %>%
    filter(between(row_number(), 4, 13))

  table <- table %>%
    rename(
      file = x1,
      surname = x2,
      first_name = x3,
      born = x4,
      title = x5,
      address = x6,
      mantal_number = x7,
      other = x8
    ) %>%
    select(1:8)
  
  # sleep a little between each request
  Sys.sleep(rnorm(1, 2, .2))
  
  table
}

# test
# get_table_data("https://sok.stadsarkivet.stockholm.se/Databas/mantalsregister-1909/Sok?sidindex=30")

```

```{r}
start_page <- 0
n_pages <- 11679

list_of_pages <- tibble(url = paste0("https://sok.stadsarkivet.stockholm.se/Databas/mantalsregister-1909/Sok?sidindex=",
                                     start_page:n_pages))

df_test <- list_of_pages %>% 
  head(5) %>% 
  mutate(data = map(url, possibly(get_table_data, "failed")))


```

